### ISSUE TITLE
Go get is error-ing

### ISSUE THREAD

**Issue by xmudrii** [golang/oauth2#205]
I was executing : `go get golang.org/x/oauth2`.
Go version:
```
go version devel +cdccd6a Sun Oct 23 14:25:29 2016 +0000 linux/amd64
```
System:
Ubuntu 16.40 Yakkety Yak
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```
```
Linux randomhostname 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I was expecting it to install.
I'm seeing:
```
# golang.org/x/net/context
../../../../golang.org/x/net/context/go18.go:17: syntax error: unexpected = in type declaration
../../../../golang.org/x/net/context/go18.go:22: syntax error: unexpected = in type declaration
```

Is it some my bad or bug?

**Comment by rakyll** [comment]
go version devel +f135106 Sun Oct 30 19:14:08 2016 +0000 darwin/amd64 is working. Please update the Go source to the HEAD and retry.

This problem is caused by https://github.com/golang/net/commit/dffc95cbb4ff9af8614b2741ec26371fffcc19b3, so you shouldn't use Go from tip prior to this specific commit.

**Comment by xmudrii** [comment]
Thank you very much. I updated Go to latest (go version devel +f135106 Sun Oct 30 19:14:08 2016 +0000 linux/amd64) and it is working. :+1:
