### ISSUE TITLE
when constructing an oauth2 client - http.Client Timeout is not passed on

### ISSUE THREAD

**Issue by zachgersh** [golang/oauth2#206]
Hey All,

I can fix this issue but I'd love to know if this was intentional. Only the values from the `HTTPClient` that pertain to the `Transport` are added to the newly constructed oauth2 client, even if you pass along a full httpclient.

as seen here (does not allow for timeout):
https://github.com/golang/oauth2/blob/master/oauth2.go#L310

only the transport is reattached:
https://github.com/golang/oauth2/blob/master/internal/transport.go#L59

Can the httpclient that is passed in be fully reconstructed? Seems pretty easy to be fixed.

**Comment by rakyll** [comment]
We designed the http.Client you can retrieve by `HTTPClient` to be used to do internal requests within the package to retrieve tokens from the OAuth2 endpoint.

On the other hand, the client returned from NewClient is used to make requests to an actual API.

It was intentional not to reuse the context http.Client. For most cases, we don't want users to know that they need to pass a http.Client in the context. It is anti pattern and absurd but helps us to support a custom http.Client against the OAuth2 provider without populating the API surface.

The better way is to modify to the Client returned from NewClient. We should probably also document that ctx.Value(HTTPClient) is only used in requests to the OAuth2 provider.

**Comment by zachgersh** [comment]
@rakyll thanks so much for the answer! I don't mind a documentation change but this seems like a sharp edge that a user could miss. If users don't end up passing an `http.Client` in the ctx we still end up with the `DefaultClient` timeouts being nicely set on the returned oauth2 client. If they are passing one in, I believe that it is safe to assume that they want the timeout / configuration values copied over. Maybe we can work toward some sort of code change that you are happy with and is more user friendly?

**Comment by zachgersh** [comment]
@rakyll wanted to poke this again - if you aren't happy with the above suggestion I can 100% just close this issue.

**Comment by rakyll** [comment]
I am not truly convinced that newly constructed clients needs to inherit its properties from the context client but I think we still need to improve the docs to make it clear this is not the case.

**Comment by zachgersh** [comment]
@rakyll thanks again - I'll take a stab at updating the docs and providing a contrived example of this (so people don't run into it). Will close this an open a PR (like issues to be nice and tidy).

**Comment by rakyll** [comment]
Sounds great, thanks @zachgersh!

**Comment by marc-coury-cko** [comment]
Just worth adding a comment here for people who arrive at this in the future. Both `NewClient` and `Config.Client` return an `*http.Client`, so you can just set the timeout on the client that is returned.
