### ISSUE TITLE
Empty context results in panic

### ISSUE THREAD

**Issue by NexoMichael** [golang/oauth2#240]
Hi,

After https://github.com/golang/oauth2/commit/626d87b99350690f6eb2b92c2f717221cdaf6f9a commit nil context used in Exchange call results in panic.
It is so because call in http.Do of ctxhttp library:
 
`resp, err := client.Do(req.WithContext(ctx))`

results in panic's if context is nil:
https://golang.org/src/net/http/request.go?s=11679:11738#L317

As result nil context is not allowed anymore in Exchange call.

**Comment by thebod** [comment]
Hi,

nil-contexts are not allowed, see https://golang.org/pkg/context/.
That's why we did not include a check/fallback for nil-contexts, discussion: https://go-review.googlesource.com/c/45370/#message-eba1ad10e31b2fecb331cf539c323f7f61dfe2d6

Does this happen in custom code, or part of this library?

**Comment by NexoMichael** [comment]
This happend in custom code. I completely understand that "nil" is something that should-not ever be used, but the issue is that used library behaviour changed without any significant notice which brake some code.

I think that issue should be closed cause nothing to be fixed here.
