### ISSUE TITLE
Azure AD package

### ISSUE THREAD

**Issue by hexadecy** [golang/oauth2#257]
More useful than the Microsoft package.
```
package azure

import (
	"golang.org/x/oauth2"
)

// Endpoint is Azure AD OAuth 2.0 endpoint.
var Endpoint = oauth2.Endpoint{
	AuthURL:  "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
	TokenURL: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
}
```

**Comment by rakyll** [comment]
I will create a change, thanks.

**Comment by rakyll** [comment]
I have one question actually before sending out the change. How does this differ from the microsoft package? Do Azure services require a different endpoint?

**Comment by hexadecy** [comment]
https://developer.microsoft.com/en-us/graph/docs/concepts/auth_overview
You must use Azure AD for Graph explorer or Office 365 REST API, more work related

Login live is more for personnal Outlook Account ect...

**Comment by rumyantseva** [comment]
Hello!

Currently, I'm working on a project where we use Azure AD OAuth2.
I noticed, that the endpoints are a bit more complicated than just `https://login.microsoftonline.com/common/...`. Sometimes instead of `common`, you might need other tenants (for more information see [the documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints)).

I suggested my changes here: https://go-review.googlesource.com/#/c/oauth2/+/82315/
I hope, this contribution might be useful.

Thank you.
