### ISSUE TITLE
proposal: define policy for new endpoint packages

### ISSUE THREAD

**Issue by bradfitz** [golang/oauth2#325]
I think we've grown too many subpackages just to defined Endpoints:

https://github.com/golang/oauth2/

<img width="593" alt="screen shot 2018-09-25 at 6 03 34 am" src="https://user-images.githubusercontent.com/2621/46016104-c354cd00-c088-11e8-97dd-736ab26d6179.png">

This pattern started with the "google" package which also contained Google-specific code that we didn't want polluting the general package.

When people started sending other endpoint packages I accepted them because "well, Google has a package and why does Google get to be special?", but I never thought about the criteria for when a package should exist.

Let's define a policy.

One strawman policy:

* must contain site-specific code other than just the Endpoint definition
* must also be a somewhat popular site (hard to objectively define)

Simpler policy:

* no new endpoint packages at all. They can all live elsewhere.

/cc @rakyll @zombiezen

**Comment by zombiezen** [comment]
In previous conversations with @rakyll, I think we've more been in favor of the latter (simpler) policy of not having endpoints live in this repository.  In practice, most all of these providers have some subtle nuances about how they should be used (what kind of credentials can be obtained, offline access, etc.) that makes sense to have live alongside the APIs they represent, instead of detached in the Go package. In this proposed end-state, `golang.org/x/oauth2` would just contain a "toolkit" of common OAuth 2.0 standard parsing functions and sample code on how to build your own endpoint package.

/cc @jadekler

**Comment by bradfitz** [comment]
@zombiezen, SGTM.

**Comment by bradfitz** [comment]
I set https://go-review.googlesource.com/c/oauth2/+/147459

**Comment by adeinega** [comment]
@rakyll, @bradfitz, https://datatracker.ietf.org/doc/html/rfc8414 could be used to get all required information about endpoints and even more.
