### ISSUE TITLE
I _think_ the build comment in appenginevm.go is incorrect?

### ISSUE THREAD

**Issue by DallanQ** [golang/oauth2#75]
It is // +build appenginevm !appengine

but I think it should be // +build appenginevm,!appengine  (note the comma)

I'm currently using this code in a compute-engine (non-appengine and non-appenginevm) environment, so I haven't included google.golang.org/appengine. I don't think I should need to include it. By AND'ing the two build conditions, the appenginevm.go file is excluded from the build. FWIW, the two build conditions are AND'ed in appengine.go.

**Comment by rakyll** [comment]
> When I go get golang.org/x/oauth2 and then try to build my project I get an error from appenginevm.go that google.golang.org/appengine can't be found.

Do you mean you're running `go get golang.org/x/oauth2/...`? Otherwise, you cant get google package or its dependencies.

> I'd rather not include google.golang.org/appengine in my compute-engine project.

Why? Why do you care what source files that goes into the build?

> Why do you have // +build appenginevm !appengine as the build comment for appenginevm.go, and // +build appengine,!appenginevm as the build comment for appengine.go?

As I said on the previous post, it simplifies the number of tags we have to care about. "appenginevm !appengine" builds with no tags and a no-tag go build/test covers most of the package. More importantly, appenginevm.go is documented by godoc when it's behind "appenginevm !appengine".  A good sacrifice it is to keep it OR'ed.

**Comment by DallanQ** [comment]
I ran `go get golang.org/x/oauth2` exactly as specified in this project's readme. I then ran `go get github.com/golang/protobuf/proto` to get the protobuf dependency. Are you saying that I should `go get` something else?

**Comment by rakyll** [comment]
We have came up with an alternative solution. See https://go-review.googlesource.com/#/c/2980/.

Closing the issue, App Engine implementations will not be required if you're not targeting an App Engine application.

**Comment by gengophers** [comment]
Thanks!
