### ISSUE TITLE
asn1 structure from jwt.Config struct

### ISSUE THREAD

**Issue by rlynjb** [golang/oauth2#83]
i've emailed @bradfitz regarding this bug..

i seem to be getting this error "asn1 structure error".. see image code below

http://screencast.com/t/QlJVTqnIlVdu

it seems like ive pinpoint that this error was coming from jwt.Config struct. ive followed the instructions on how to fill in the fields for token.. im wondering if this is a private key error? am i missing a step here, ive found a function at oauth2/internal called ParseKey.. is that something that i need to do first?

**Comment by jfcote87** [comment]
I duplicated the error by using an invalid PEM encoding so the problem is with the error reporting.  When internal.ParseKey encounters a PEM error, it assumes that "key" is either in a PKSC8 or PKCS1 format and attempts to parse "key" using these formats.  The error then comes from the x509.ParsePKCS1PrivateKey(key) [line 31] and isn't very helpful.

Shouldn't the Config.PrivateKey just be an rsa.PrivateKey rather than []byte?  

This causes the error to occur when Config refreshes the token rather  than when it is instantiated.

**Comment by rakyll** [comment]
Can you just give me a sample private key and steps to reproduce the problem? Private emails to Brad or attaching not-working screenshots is not how you file issues.

We don't mutate Config.PrivateKey anywhere, I'm failing to understand why it suddenly doesn't work after the refresh.

The field is a byte slice for connivence, I don't want to figure out the encoding of the key.

**Comment by jfcote87** [comment]
My understanding from working with rlynjb is that the error was returned right away, not during the refresh. No valid toke was ever returned. I believe that her pem encoded array was corrupted via  fat fingering, a bad paste or misuse of escape characters.  The gist below shows how an improperly encoded pem returns an unhelpful "an1: structure error...". 

https://gist.github.com/jfcote87/4fa7387925b99a7b7808

Easy to fix, change line 33 of internal/oauth2.go to read
return nil, errors.New("oauth2: Config.PrivateKey is not encoded in a correct PEM, PKCS1 or PKCS8 format.")

My only quibble is that we don't know if a key is valid until the first call to jwtSource.Token() but I agree that the change isn't really worth the cost.

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/5423/.
